name: 'Publish - npm'
on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  publish:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/publish-npm.yml@16e92b2ce51488d5ab27223b4ae8873eaebfef68
    secrets: inherit
