name: 'Publish - npm'
on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  publish:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/publish-npm.yml@04630ab07399d9a5c7670141bb80429810e055c8
    secrets: inherit
