name: 'Publish - npm'
on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  publish:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/publish-npm.yml@88fbc036cdac69fa2dd1f1c4c6a9e122b367393d
    secrets: inherit
