name: 'SemVer Check'
on:
  pull_request:
    types: [ labeled, unlabeled, opened, reopened, synchronize ]

jobs:
  check:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/semver-check.yml@a0f97aa67dc4ae9b060ecb383591f863112258b5
